In [1]:
import numpy as np 
group_1= np.array([1000, 1380, 1200])
group_2= np.array([1400, 1600, 1180, 1220])
gr =np.concatenate((group_1,group_2))
gr= np.sort(gr)
gr
x= len(gr)
x

7

In [2]:
from math import factorial
# хотим проверить что событие произойдет k раз из n
def comb(n, k):
    return factorial(n)/(factorial(k)*factorial(n-k))
n = 7
k = 3
print(comb(n,k))

35.0


1. 123
2. 124
3. 125
4. 126
5. 127
6. 134
7. 135
8. 136
9. 137
10. 145
11. 146
12. 147
13. 156
14. 157
15. 167
16. 234
17. 235
18. 236
19. 237
20. 245
21. 246
22. 247
23. 256
24. 257
25. 267
26. 345
27. 346
28. 347
29. 356
30. 357
31. 367 - 
32. 456 - 15
33. 457 - 16
34. 467 - 17
35. 567 - 18

6: 1 раз
7: 1 раз
8: 2 раза
9: 3 раза
10: 4 раза
11: 4 раза
12: 5 раз
13: 4 раза
14: 4 раза
15: 3 раза
16: 2 раза
17: 1 раз
18: 1 раз

In [3]:
s = 1/35
s

0.02857142857142857

Средние расходы на обследование одного больного до ознакомления с расходами коллег

X= np.array([20,17, 14, 42, 50, 62, 8, 49, 81, 54, 48, 55, 56])

Y= np.array ([20, 26, 1, 24, 1, 47, 15, 7, 65, 9, 21, 36, 30])

Средние расходы на лечение одного больного до ознакомления с расходами коллег

X= np.array([ 32, 41, 51, 29, 76, 47, 60, 58, 40, 64, 73, 66, 73])

Y= np.array ([42, 90, 71, 47, 56, 43, 137, 63, 28, 60, 87, 69, 50])

Произошли ли изменения на расходы и лечение?


In [13]:
import scipy.stats as stats
X= np.array([20, 17, 14, 42, 50, 62, 8, 49, 81, 54, 48, 55, 56])
Y= np.array ([20, 26, 1, 24, 1, 47, 15, 7, 65, 9, 21, 36, 30])
print (stats.wilcoxon(X,Y))
delta=Y-X

for i in delta:
    delta = abs(delta)
delta

WilcoxonResult(statistic=3.0, pvalue=0.004741768038406971)


array([ 0,  9, 13, 18, 49, 15,  7, 42, 16, 45, 27, 19, 26])

In [5]:
gr= np.sort(delta)
gr

array([ 0,  7,  9, 13, 15, 16, 18, 19, 26, 27, 42, 45, 49])

In [6]:
X= np.array([ 32, 41, 51, 29, 76, 47, 60, 58, 40, 64, 73, 66, 73])
Y= np.array ([42, 90, 71, 47, 56, 43, 137, 63, 28, 60, 87, 69, 50])
print (stats.wilcoxon(X,Y))
delta=Y-X

for i in delta:
    delta = abs(delta)
delta


WilcoxonResult(statistic=31.5, pvalue=0.339599609375)


array([10, 49, 20, 18, 20,  4, 77,  5, 12,  4, 14,  3, 23])

In [7]:
gr= np.sort(delta)
gr

array([ 3,  4,  4,  5, 10, 12, 14, 18, 20, 20, 23, 49, 77])

In [8]:
w=9.5+2.5+6+2.5+11
w

31.5

In [9]:
A = np.array([3.5, 3.3, 4.9, 3.6])
B = np.array([8.6, 5.4, 8.8, 5.6])
C = np.array([5.1, 8.6, 7.7, 5.0])
gr = np.concatenate((A,B,C))
gr = np.sort(gr)
print(gr)

[3.3 3.5 3.6 4.9 5.  5.1 5.4 5.6 7.7 8.6 8.6 8.8]


In [10]:
R1= 4
R2 = 11
R3 = 9
## R = n(k+1)/2= 4*(3+1)/2=8
Rs= 8

In [11]:
x= (12/(4*3*4))*(16+9+1)
x

6.5

In [12]:
h= (12/(15*16))*((16**2+39**2+65**2)/5)-48
h

12.02000000000001