In [7]:
import numpy as np
import matplotlib.pyplot as plt

x1 = np.array([10,8, 13, 9,11,14, 6,4,12, 7,5])
y1 = np.array([8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68 ])
x2= np.array([ 10,8, 13, 9,11,14, 6,4,12, 7,5 ])
y2 = np.array([ 9.14, 8.14, 8.74,8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74])
x3= np.array([ 10,8, 13, 9,11,14, 6,4,12, 7,5 ])
y3 = np.array([7.46,6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73])
x4 = np.array([8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8])
y4 = np.array([6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25,12.5, 5.56, 7.91, 6.89])
x5= np.array([ 10, 8, 13, 9, 11, 14, 6, 4, 12, 7,5, 15, 16, 18 ])
y5 = np.array([ 9.14, 8.14, 8.74,8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74, 6.5, 5, 2.9])

In [8]:
np.corrcoef(x1,y1)

array([[1.        , 0.81642052],
       [0.81642052, 1.        ]])

In [9]:
np.corrcoef(x2,y2)

array([[1.        , 0.81623651],
       [0.81623651, 1.        ]])

In [10]:
np.corrcoef(x3,y3)

array([[1.        , 0.81628674],
       [0.81628674, 1.        ]])

In [11]:
np.corrcoef(x4,y4)

array([[1.        , 0.81652144],
       [0.81652144, 1.        ]])

In [12]:
np.corrcoef(x5,y5)

array([[1.        , 0.02245218],
       [0.02245218, 1.        ]])

In [14]:
import pandas as pd

In [ ]:
df= pd.DataFrame({"x1":x1,"y1":y1}, columns=[x1,y1])